-- IXL Student Portal - Production SQL Setup
-- Run this in your Supabase SQL Editor

-- 1. Students Table
CREATE TABLE IF NOT EXISTS students (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT NOT NULL,
  roll_number TEXT UNIQUE,
  course TEXT,
  year_sem TEXT,
  avatar_url TEXT,
  gpa DECIMAL(3,2),
  attendance_percent DECIMAL(5,2),
  total_credits INTEGER,
  email TEXT
);

-- 2. Assignments Table
CREATE TABLE IF NOT EXISTS assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES auth.users NOT NULL,
  title TEXT NOT NULL,
  subject TEXT,
  category TEXT,
  deadline TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'pending',
  priority TEXT,
  submitted_on TIMESTAMP WITH TIME ZONE,
  grade TEXT
);

-- 3. Fees Table
CREATE TABLE IF NOT EXISTS fees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES auth.users NOT NULL,
  type TEXT NOT NULL,
  amount DECIMAL(10,2),
  due_date DATE,
  status TEXT
);

-- 4. Enable RLS
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE fees ENABLE ROW LEVEL SECURITY;

-- 5. Access Policies
CREATE POLICY "Users can view own profile" ON students FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON students FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON students FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can view own assignments" ON assignments FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Users can view own fees" ON fees FOR SELECT USING (auth.uid() = student_id);
